import type { UIStrings } from "./types";

export const en: UIStrings = {
  nav: {
    home: "Home",
    services: "Services",
    notices: "Notices",
    meetings: "Meetings",
    forms: "Forms",
    contact: "Contact",
  },
  banner: {
    demo: "Demonstration site. This is a fictional agency built as a portfolio example and is not affiliated with any government entity.",
  },
  header: {
    searchPlaceholder: "Search this site",
    searchLabel: "Search this site",
    languageToggleToEs: "Switch to Español",
    languageToggleToEn: "Switch to English",
    skipLink: "Skip to main content",
    mobileNavOpen: "Open menu",
    mobileNavClose: "Close menu",
    agencyName: "City of Bellwood",
    agencyParent: "Department of Public Works",
    seatUnder: "Decrease text size",
    seatOver: "Increase text size",
    seatReset: "Reset text size",
    contactLink: "Contact",
    quickActionsHeading: "I Want To...",
    navDropdownOpen: "Show submenu for",
    navDropdownClose: "Hide submenu for",
  },
  footer: {
    contactHeading: "Contact Bellwood Public Works",
    officeHoursHeading: "Office Hours",
    officeHours: "Monday through Friday, 8:00 AM to 4:30 PM. Closed on observed city holidays.",
    address: "100 Municipal Way, Bellwood, ST 55501",
    phone: "(555) 011-2200",
    tty: "TTY: (555) 011-2299",
    phone2: "Non-emergency after hours: (555) 011-2911",
    email: "info@bellwoodpublicworks.example",
    accessibilityStatement: "Accessibility Statement",
    nonDiscrimination:
      "Bellwood Public Works does not discriminate on the basis of race, color, national origin, sex, age, or disability in the provision of services or employment opportunities. Complaints may be filed with the Office of Civil Rights.",
    publicRecords: "Public Records Request",
    privacyPolicy: "Privacy Policy",
    siteMap: "Site Map",
    departmentsHeading: "Departments",
    servicesHeading: "Services",
    resourcesHeading: "Resources",
    connectHeading: "Connect",
    copyright: "City of Bellwood. This is a demonstration website and does not represent a real municipality.",
    designedBy: "Designed by",
    backToTop: "Back to top",
  },
  alert: {
    urgentLabel: "Urgent notice",
    archivedLabel: "Archived",
  },
  home: {
    heading: "Welcome to Bellwood Public Works",
    intro:
      "Bellwood Public Works maintains the infrastructure and services that keep our community running, from clean water and safe streets to parks and permitting. Find the service you need below.",
    servicesCta: "Browse services",
    noticesCta: "View current notices",
    meetingsCta: "See upcoming meetings",
    formsCta: "Download forms",
    alertsHeading: "Active Alerts",
    noAlertsMessage: "There are no active urgent alerts at this time.",
    quickLinksHeading: "Quick Links",
    upcomingMeetingsHeading: "Upcoming Meetings",
    viewAllMeetings: "View all meetings",
    recentNoticesHeading: "Recent Notices",
    viewAllNotices: "View all notices",
  },
  pages: {
    servicesHeading: "Services",
    servicesIntro:
      "Browse the services provided by Bellwood Public Works, including utilities, permitting, and infrastructure maintenance.",
    noticesHeading: "Public Notices",
    noticesIntro:
      "Current and recent public notices from Bellwood Public Works, including service disruptions and closures.",
    meetingsHeading: "Public Meetings",
    meetingsIntro: "Upcoming and recent meetings of the City Council, Planning Commission, and advisory boards.",
    formsHeading: "Forms and Applications",
    formsIntro: "Download permit applications, service request forms, and other documents.",
    contactHeading: "Contact Us",
    contactIntro:
      "Reach Bellwood Public Works by phone, email, or the form below, or find the direct line for a specific division in the department directory.",
    contactDirectoryHeading: "Department Directory",
    contactDirectoryCaption: "Bellwood Public Works department directory",
    contactDirectoryDepartmentColumn: "Department",
    contactDirectoryPhoneColumn: "Phone",
    contactDirectoryEmailColumn: "Email",
    staffDirectoryHeading: "Staff Directory",
    staffDirectoryIntro: "Division leads and their teams are available during regular office hours listed above.",
  },
  serviceDetail: {
    appliesToHeading: "Who this applies to",
    howToApplyHeading: "How to apply",
    relatedFormsHeading: "Related forms",
    contactHeading: "Contact",
    backLink: "Back to Services",
  },
  noticeDetail: {
    postedLabel: "Posted",
    departmentLabel: "Department",
    backLink: "Back to Notices",
  },
  services: {
    categoryFilterLabel: "Filter by category",
    allCategoriesLabel: "All categories",
    resultsCount: "Showing {count} of {total} services",
    emptyState: "No services match the selected category.",
  },
  notices: {
    yearFilterLabel: "Filter by year",
    allYearsLabel: "All years",
    resultsCount: "Showing {count} of {total} notices",
    emptyState: "No notices match the selected year.",
  },
  meetings: {
    agendaLabel: "Agenda",
    minutesLabel: "Minutes",
    upcomingHeading: "Upcoming Meetings",
    pastHeading: "Past Meetings",
    noUpcoming: "There are no upcoming meetings scheduled at this time.",
    noPast: "There are no past meetings to display.",
    atTime: "at",
    forLabel: "for",
    pdfFormat: "PDF",
  },
  forms: {
    searchLabel: "Search forms",
    searchPlaceholder: "Search by title or description",
    categoryFilterLabel: "Filter by category",
    allCategoriesLabel: "All categories",
    resultsCount: "Showing {count} of {total} forms",
    emptyState: "No forms match your search.",
    lastUpdatedLabel: "Last updated",
    fileSizeLabel: "File size",
  },
  contactForm: {
    legendYourInfo: "Your information",
    legendYourMessage: "Your message",
    nameLabel: "Full name",
    nameRequiredError: "Enter your full name.",
    emailLabel: "Email address",
    emailRequiredError: "Enter your email address.",
    emailFormatError: "Enter a valid email address.",
    phoneLabel: "Phone number",
    phoneOptional: "optional",
    departmentLabel: "Department",
    departmentOptional: "optional",
    departmentPlaceholder: "Select a department",
    messageLabel: "Message",
    messageRequiredError: "Enter a message.",
    errorSummaryHeading: "There is a problem with your submission",
    submitLabel: "Send message",
    successMessage: "Thank you. Your message has been received.",
    demoNote: "This is a demonstration form. Submissions are not sent or stored.",
    requiredMarker: "required",
  },
  accessibility: {
    heading: "Accessibility Statement",
    intro:
      "Bellwood Public Works is committed to ensuring digital accessibility for people of all abilities. We are actively working to increase the accessibility and usability of this website.",
    standardsHeading: "Conformance Status",
    standardsBody:
      "This website aims to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 Level AA and Section 508 of the Rehabilitation Act. These standards cover keyboard navigation, visible focus indicators, sufficient color contrast, semantic landmarks, meaningful alternative text for images, and a logical heading structure.",
    feedbackHeading: "Feedback",
    feedbackBody:
      "We welcome your feedback on the accessibility of this website. If you encounter an accessibility barrier, please let us know using the contact form so we can address it.",
    contactLinkLabel: "Contact Bellwood Public Works",
  },
  breadcrumbs: {
    homeLabel: "Home",
  },
  sectionNav: {
    heading: "In this section",
    toggleLabel: "In this section",
  },
  lastUpdated: {
    label: "Page last updated",
  },
  pageHelpful: {
    question: "Was this page helpful?",
    yes: "Yes",
    no: "No",
    thanksYes: "Thank you for your feedback.",
    thanksNo: "Thank you. Tell us more using the contact form.",
  },
  sidebar: {
    contactHeading: "Responsible Division",
    callLabel: "Call",
    emailLabel: "Email",
    hoursLabel: "Hours",
    relatedDocumentsHeading: "Related Documents",
    relatedLinksHeading: "Related Links",
  },
};
