import type { UIStrings } from "./types";

export const es: UIStrings = {
  nav: {
    home: "Inicio",
    services: "Servicios",
    notices: "Avisos",
    meetings: "Reuniones",
    forms: "Formularios",
    contact: "Contacto",
  },
  banner: {
    demo: "Sitio de demostración. Esta es una agencia ficticia creada como ejemplo de portafolio y no está afiliada a ninguna entidad gubernamental.",
  },
  header: {
    searchPlaceholder: "Buscar en este sitio",
    searchLabel: "Buscar en este sitio",
    languageToggleToEs: "Cambiar a Español",
    languageToggleToEn: "Cambiar a inglés",
    skipLink: "Saltar al contenido principal",
    mobileNavOpen: "Abrir menú",
    mobileNavClose: "Cerrar menú",
    agencyName: "Ciudad de Bellwood",
    agencyParent: "Departamento de Obras Públicas",
    seatUnder: "Disminuir tamaño de texto",
    seatOver: "Aumentar tamaño de texto",
    seatReset: "Restablecer tamaño de texto",
    contactLink: "Contacto",
    quickActionsHeading: "Quiero...",
    navDropdownOpen: "Mostrar submenú de",
    navDropdownClose: "Ocultar submenú de",
  },
  footer: {
    contactHeading: "Contacte a Bellwood Public Works",
    officeHoursHeading: "Horario de Oficina",
    officeHours: "Lunes a viernes, de 8:00 AM a 4:30 PM. Cerrado los días feriados observados por la ciudad.",
    address: "100 Municipal Way, Bellwood, ST 55501",
    phone: "(555) 011-2200",
    tty: "TTY: (555) 011-2299",
    phone2: "Línea no urgente fuera de horario: (555) 011-2911",
    email: "info@bellwoodpublicworks.example",
    accessibilityStatement: "Declaración de Accesibilidad",
    nonDiscrimination:
      "Bellwood Public Works no discrimina por motivos de raza, color, origen nacional, sexo, edad o discapacidad en la prestación de servicios ni en las oportunidades de empleo. Las quejas pueden presentarse ante la Oficina de Derechos Civiles.",
    publicRecords: "Solicitud de Registros Públicos",
    privacyPolicy: "Política de Privacidad",
    siteMap: "Mapa del Sitio",
    departmentsHeading: "Departamentos",
    servicesHeading: "Servicios",
    resourcesHeading: "Recursos",
    connectHeading: "Contáctenos",
    copyright: "Ciudad de Bellwood. Este es un sitio web de demostración y no representa a un municipio real.",
    designedBy: "Diseñado por",
    backToTop: "Volver arriba",
  },
  alert: {
    urgentLabel: "Aviso urgente",
    archivedLabel: "Archivado",
  },
  home: {
    heading: "Bienvenido a Bellwood Public Works",
    intro:
      "Bellwood Public Works mantiene la infraestructura y los servicios que hacen funcionar a nuestra comunidad, desde agua potable y calles seguras hasta parques y permisos. Encuentre el servicio que necesita a continuación.",
    servicesCta: "Explorar servicios",
    noticesCta: "Ver avisos actuales",
    meetingsCta: "Ver próximas reuniones",
    formsCta: "Descargar formularios",
    alertsHeading: "Alertas Activas",
    noAlertsMessage: "No hay alertas urgentes activas en este momento.",
    quickLinksHeading: "Enlaces Rápidos",
    upcomingMeetingsHeading: "Próximas Reuniones",
    viewAllMeetings: "Ver todas las reuniones",
    recentNoticesHeading: "Avisos Recientes",
    viewAllNotices: "Ver todos los avisos",
  },
  pages: {
    servicesHeading: "Servicios",
    servicesIntro:
      "Explore los servicios que ofrece Bellwood Public Works, incluyendo servicios públicos, permisos y mantenimiento de infraestructura.",
    noticesHeading: "Avisos Públicos",
    noticesIntro:
      "Avisos públicos actuales y recientes de Bellwood Public Works, incluyendo interrupciones de servicio y cierres.",
    meetingsHeading: "Reuniones Públicas",
    meetingsIntro:
      "Próximas y recientes reuniones del Concejo Municipal, la Comisión de Planificación y las juntas asesoras.",
    formsHeading: "Formularios y Solicitudes",
    formsIntro: "Descargue solicitudes de permisos, formularios de solicitud de servicio y otros documentos.",
    contactHeading: "Contáctenos",
    contactIntro:
      "Comuníquese con Bellwood Public Works por teléfono, correo electrónico o el formulario a continuación, o encuentre la línea directa de una división específica en el directorio de departamentos.",
    contactDirectoryHeading: "Directorio de Departamentos",
    contactDirectoryCaption: "Directorio de departamentos de Bellwood Public Works",
    contactDirectoryDepartmentColumn: "Departamento",
    contactDirectoryPhoneColumn: "Teléfono",
    contactDirectoryEmailColumn: "Correo electrónico",
    staffDirectoryHeading: "Directorio de Personal",
    staffDirectoryIntro:
      "Los jefes de división y sus equipos están disponibles durante el horario regular de oficina indicado arriba.",
  },
  serviceDetail: {
    appliesToHeading: "A quién aplica",
    howToApplyHeading: "Cómo solicitar",
    relatedFormsHeading: "Formularios relacionados",
    contactHeading: "Contacto",
    backLink: "Volver a Servicios",
  },
  noticeDetail: {
    postedLabel: "Publicado",
    departmentLabel: "Departamento",
    backLink: "Volver a Avisos",
  },
  services: {
    categoryFilterLabel: "Filtrar por categoría",
    allCategoriesLabel: "Todas las categorías",
    resultsCount: "Mostrando {count} de {total} servicios",
    emptyState: "Ningún servicio coincide con la categoría seleccionada.",
  },
  notices: {
    yearFilterLabel: "Filtrar por año",
    allYearsLabel: "Todos los años",
    resultsCount: "Mostrando {count} de {total} avisos",
    emptyState: "Ningún aviso coincide con el año seleccionado.",
  },
  meetings: {
    agendaLabel: "Agenda",
    minutesLabel: "Actas",
    upcomingHeading: "Próximas Reuniones",
    pastHeading: "Reuniones Pasadas",
    noUpcoming: "No hay reuniones próximas programadas en este momento.",
    noPast: "No hay reuniones pasadas para mostrar.",
    atTime: "a las",
    forLabel: "de",
    pdfFormat: "PDF",
  },
  forms: {
    searchLabel: "Buscar formularios",
    searchPlaceholder: "Buscar por título o descripción",
    categoryFilterLabel: "Filtrar por categoría",
    allCategoriesLabel: "Todas las categorías",
    resultsCount: "Mostrando {count} de {total} formularios",
    emptyState: "Ningún formulario coincide con su búsqueda.",
    lastUpdatedLabel: "Última actualización",
    fileSizeLabel: "Tamaño del archivo",
  },
  contactForm: {
    legendYourInfo: "Su información",
    legendYourMessage: "Su mensaje",
    nameLabel: "Nombre completo",
    nameRequiredError: "Ingrese su nombre completo.",
    emailLabel: "Correo electrónico",
    emailRequiredError: "Ingrese su correo electrónico.",
    emailFormatError: "Ingrese un correo electrónico válido.",
    phoneLabel: "Número de teléfono",
    phoneOptional: "opcional",
    departmentLabel: "Departamento",
    departmentOptional: "opcional",
    departmentPlaceholder: "Seleccione un departamento",
    messageLabel: "Mensaje",
    messageRequiredError: "Ingrese un mensaje.",
    errorSummaryHeading: "Hay un problema con su envío",
    submitLabel: "Enviar mensaje",
    successMessage: "Gracias. Su mensaje ha sido recibido.",
    demoNote: "Este es un formulario de demostración. Los envíos no se envían ni se almacenan.",
    requiredMarker: "obligatorio",
  },
  accessibility: {
    heading: "Declaración de Accesibilidad",
    intro:
      "Bellwood Public Works se compromete a garantizar la accesibilidad digital para personas de todas las capacidades. Estamos trabajando activamente para aumentar la accesibilidad y usabilidad de este sitio web.",
    standardsHeading: "Estado de Conformidad",
    standardsBody:
      "Este sitio web tiene como objetivo cumplir con las Pautas de Accesibilidad para el Contenido Web (WCAG) 2.1 Nivel AA y la Sección 508 de la Ley de Rehabilitación. Estos estándares cubren la navegación por teclado, indicadores de enfoque visibles, contraste de color suficiente, puntos de referencia semánticos, texto alternativo significativo para imágenes y una estructura de encabezados lógica.",
    feedbackHeading: "Comentarios",
    feedbackBody:
      "Agradecemos sus comentarios sobre la accesibilidad de este sitio web. Si encuentra una barrera de accesibilidad, avísenos mediante el formulario de contacto para que podamos solucionarlo.",
    contactLinkLabel: "Contacte a Bellwood Public Works",
  },
  breadcrumbs: {
    homeLabel: "Inicio",
  },
  sectionNav: {
    heading: "En esta sección",
    toggleLabel: "En esta sección",
  },
  lastUpdated: {
    label: "Página actualizada por última vez",
  },
  pageHelpful: {
    question: "¿Fue útil esta página?",
    yes: "Sí",
    no: "No",
    thanksYes: "Gracias por sus comentarios.",
    thanksNo: "Gracias. Cuéntenos más usando el formulario de contacto.",
  },
  sidebar: {
    contactHeading: "División Responsable",
    callLabel: "Llamar",
    emailLabel: "Correo electrónico",
    hoursLabel: "Horario",
    relatedDocumentsHeading: "Documentos Relacionados",
    relatedLinksHeading: "Enlaces Relacionados",
  },
};
