import type { FormDoc } from "./types";

export const forms: FormDoc[] = [
  {
    id: "residential-building-permit",
    title: "Residential Building Permit Application",
    description:
      "Required for additions, accessory structures, and interior renovations affecting structural elements.",
    category: "Permits",
    fileUrl: "/documents/forms/residential-building-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "210 KB",
    lastUpdated: "2026-02-10",
    es: {
      title: "Solicitud de Permiso de Construcción Residencial",
      description:
        "Requerido para ampliaciones, estructuras accesorias y renovaciones interiores que afecten elementos estructurales.",
      category: "Permisos",
    },
  },
  {
    id: "commercial-building-permit",
    title: "Commercial Building Permit Application",
    description: "Required for new construction, tenant build-outs, and major renovations to commercial properties.",
    category: "Permits",
    fileUrl: "/documents/forms/commercial-building-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "268 KB",
    lastUpdated: "2026-02-10",
    es: {
      title: "Solicitud de Permiso de Construcción Comercial",
      description:
        "Requerido para nueva construcción, adecuaciones de inquilinos y renovaciones mayores a propiedades comerciales.",
      category: "Permisos",
    },
  },
  {
    id: "right-of-way-permit",
    title: "Right-of-Way Work Permit",
    description:
      "Required before performing excavation or utility work within a public street or sidewalk right-of-way.",
    category: "Permits",
    fileUrl: "/documents/forms/right-of-way-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "224 KB",
    lastUpdated: "2026-01-08",
    es: {
      title: "Permiso de Trabajo en Derecho de Vía",
      description:
        "Requerido antes de realizar excavación o trabajos de servicios públicos dentro de un derecho de vía público de calle o acera.",
      category: "Permisos",
    },
  },
  {
    id: "driveway-apron-permit",
    title: "Driveway Apron Permit Application",
    description:
      "Required for installing or replacing a driveway apron connecting private property to a public street.",
    category: "Permits",
    fileUrl: "/documents/forms/driveway-apron-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "142 KB",
    lastUpdated: "2025-09-19",
    es: {
      title: "Solicitud de Permiso de Entrada de Vehículos",
      description:
        "Requerido para instalar o reemplazar una entrada de vehículos que conecte una propiedad privada con una calle pública.",
      category: "Permisos",
    },
  },
  {
    id: "encroachment-permit",
    title: "Right-of-Way Encroachment Permit",
    description: "Required for structures, landscaping, or fencing that extend into the public right-of-way.",
    category: "Permits",
    fileUrl: "/documents/forms/encroachment-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "176 KB",
    lastUpdated: "2025-11-03",
    es: {
      title: "Permiso de Invasión del Derecho de Vía",
      description: "Requerido para estructuras, jardinería o cercas que se extiendan hacia el derecho de vía público.",
      category: "Permisos",
    },
  },
  {
    id: "sign-permit-application",
    title: "Commercial Sign Permit Application",
    description: "Required for installing or replacing exterior signage on a commercial property.",
    category: "Permits",
    fileUrl: "/documents/forms/sign-permit-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "188 KB",
    lastUpdated: "2025-05-27",
    es: {
      title: "Solicitud de Permiso de Letrero Comercial",
      description: "Requerido para instalar o reemplazar señalización exterior en una propiedad comercial.",
      category: "Permisos",
    },
  },
  {
    id: "demolition-permit",
    title: "Demolition Permit Application",
    description: "Required before demolishing or removing any portion of a residential or commercial structure.",
    category: "Permits",
    fileUrl: "/documents/forms/demolition-permit.pdf",
    fileType: "PDF",
    fileSizeLabel: "154 KB",
    lastUpdated: "2025-07-14",
    es: {
      title: "Solicitud de Permiso de Demolición",
      description: "Requerido antes de demoler o remover cualquier parte de una estructura residencial o comercial.",
      category: "Permisos",
    },
  },
  {
    id: "variance-application",
    title: "Zoning Variance Application",
    description: "Request a variance from setback, height, or lot coverage requirements under the zoning ordinance.",
    category: "Applications",
    fileUrl: "/documents/forms/variance-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "204 KB",
    lastUpdated: "2025-10-16",
    es: {
      title: "Solicitud de Variancia de Zonificación",
      description:
        "Solicite una variancia a los requisitos de retiro, altura o cobertura de lote bajo la ordenanza de zonificación.",
      category: "Solicitudes",
    },
  },
  {
    id: "rezoning-application",
    title: "Rezoning Application",
    description: "Submit a request to change the zoning classification of a specific parcel or group of parcels.",
    category: "Applications",
    fileUrl: "/documents/forms/rezoning-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "232 KB",
    lastUpdated: "2026-03-01",
    es: {
      title: "Solicitud de Recalificación de Zonificación",
      description:
        "Presente una solicitud para cambiar la clasificación de zonificación de una parcela o grupo de parcelas específico.",
      category: "Solicitudes",
    },
  },
  {
    id: "pavilion-reservation",
    title: "Park Pavilion Reservation Form",
    description: "Reserve a park pavilion or athletic field for a private event or organized activity.",
    category: "Applications",
    fileUrl: "/documents/forms/pavilion-reservation.pdf",
    fileType: "PDF",
    fileSizeLabel: "158 KB",
    lastUpdated: "2026-04-01",
    es: {
      title: "Formulario de Reserva de Pabellón de Parque",
      description: "Reserve un pabellón de parque o campo deportivo para un evento privado o actividad organizada.",
      category: "Solicitudes",
    },
  },
  {
    id: "special-event-application",
    title: "Special Event Permit Application",
    description:
      "Required for parades, block parties, races, or other events that will use a public street, sidewalk, or park.",
    category: "Applications",
    fileUrl: "/documents/forms/special-event-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "246 KB",
    lastUpdated: "2026-05-11",
    es: {
      title: "Solicitud de Permiso para Evento Especial",
      description:
        "Requerido para desfiles, fiestas de cuadra, carreras u otros eventos que utilicen una calle pública, acera o parque.",
      category: "Solicitudes",
    },
  },
  {
    id: "recreation-program-registration",
    title: "Recreation Program Registration Form",
    description:
      "Register for a seasonal youth or adult recreation program offered through the Parks and Recreation Division.",
    category: "Applications",
    fileUrl: "/documents/forms/recreation-program-registration.pdf",
    fileType: "PDF",
    fileSizeLabel: "132 KB",
    lastUpdated: "2026-01-15",
    es: {
      title: "Formulario de Inscripción a Programa Recreativo",
      description:
        "Inscríbase en un programa recreativo de temporada para jóvenes o adultos ofrecido por la División de Parques y Recreación.",
      category: "Solicitudes",
    },
  },
  {
    id: "employment-application",
    title: "Public Works Employment Application",
    description: "General application for open positions within the Bellwood Public Works Department.",
    category: "Applications",
    fileUrl: "/documents/forms/employment-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "198 KB",
    lastUpdated: "2025-08-22",
    es: {
      title: "Solicitud de Empleo en Obras Públicas",
      description: "Solicitud general para puestos vacantes dentro del Departamento de Obras Públicas de Bellwood.",
      category: "Solicitudes",
    },
  },
  {
    id: "service-request-form",
    title: "General Service Request Form",
    description:
      "Report a pothole, sidewalk hazard, malfunctioning streetlight, or other non-emergency maintenance issue.",
    category: "Reports",
    fileUrl: "/documents/forms/service-request-form.pdf",
    fileType: "PDF",
    fileSizeLabel: "112 KB",
    lastUpdated: "2026-03-05",
    es: {
      title: "Formulario General de Solicitud de Servicio",
      description:
        "Reporte un bache, un riesgo en la acera, una luz de calle que no funciona u otro problema de mantenimiento que no sea una emergencia.",
      category: "Informes",
    },
  },
  {
    id: "sewer-backup-report",
    title: "Sewer Backup Report Form",
    description: "Report a sewer backup or overflow affecting a residential or commercial property.",
    category: "Reports",
    fileUrl: "/documents/forms/sewer-backup-report.pdf",
    fileType: "PDF",
    fileSizeLabel: "118 KB",
    lastUpdated: "2025-06-30",
    es: {
      title: "Formulario de Reporte de Retroceso de Alcantarillado",
      description:
        "Reporte un retroceso o desbordamiento de alcantarillado que afecte una propiedad residencial o comercial.",
      category: "Informes",
    },
  },
  {
    id: "water-quality-complaint",
    title: "Water Quality Complaint Form",
    description: "Report discolored water, unusual odor or taste, or low water pressure at a specific address.",
    category: "Reports",
    fileUrl: "/documents/forms/water-quality-complaint.pdf",
    fileType: "PDF",
    fileSizeLabel: "108 KB",
    lastUpdated: "2025-07-08",
    es: {
      title: "Formulario de Queja por Calidad del Agua",
      description: "Reporte agua decolorada, olor o sabor inusual, o baja presión de agua en una dirección específica.",
      category: "Informes",
    },
  },
  {
    id: "streetlight-outage-report",
    title: "Streetlight Outage Report Form",
    description:
      "Report a streetlight that is out, flickering, or damaged, including the nearest pole number if known.",
    category: "Reports",
    fileUrl: "/documents/forms/streetlight-outage-report.pdf",
    fileType: "PDF",
    fileSizeLabel: "96 KB",
    lastUpdated: "2025-04-21",
    es: {
      title: "Formulario de Reporte de Luz de Calle Apagada",
      description:
        "Reporte una luz de calle apagada, parpadeante o dañada, incluyendo el número del poste más cercano si lo conoce.",
      category: "Informes",
    },
  },
  {
    id: "illegal-dumping-report",
    title: "Illegal Dumping Report Form",
    description: "Report illegal dumping on public property, in a storm drain, or along a waterway.",
    category: "Reports",
    fileUrl: "/documents/forms/illegal-dumping-report.pdf",
    fileType: "PDF",
    fileSizeLabel: "104 KB",
    lastUpdated: "2025-05-06",
    es: {
      title: "Formulario de Reporte de Vertido Ilegal",
      description:
        "Reporte vertido ilegal en propiedad pública, en un drenaje pluvial o a lo largo de una vía fluvial.",
      category: "Informes",
    },
  },
  {
    id: "tree-hazard-report",
    title: "Hazardous Tree Report Form",
    description: "Report a damaged, diseased, or fallen tree on public property or overhanging a public right-of-way.",
    category: "Reports",
    fileUrl: "/documents/forms/tree-hazard-report.pdf",
    fileType: "PDF",
    fileSizeLabel: "116 KB",
    lastUpdated: "2025-09-02",
    es: {
      title: "Formulario de Reporte de Árbol Peligroso",
      description:
        "Reporte un árbol dañado, enfermo o caído en propiedad pública o que sobresalga hacia un derecho de vía público.",
      category: "Informes",
    },
  },
  {
    id: "public-records-request",
    title: "Public Records Request Form",
    description:
      "Submit a formal request for public records maintained by Bellwood Public Works under the state open records law.",
    category: "Public Records",
    fileUrl: "/documents/forms/public-records-request.pdf",
    fileType: "PDF",
    fileSizeLabel: "134 KB",
    lastUpdated: "2025-11-14",
    es: {
      title: "Formulario de Solicitud de Registros Públicos",
      description:
        "Presente una solicitud formal de registros públicos que mantiene Bellwood Public Works bajo la ley estatal de registros abiertos.",
      category: "Registros Públicos",
    },
  },
  {
    id: "records-request-fee-waiver",
    title: "Public Records Fee Waiver Request",
    description: "Request a waiver or reduction of copying fees associated with a public records request.",
    category: "Public Records",
    fileUrl: "/documents/forms/records-request-fee-waiver.pdf",
    fileType: "PDF",
    fileSizeLabel: "88 KB",
    lastUpdated: "2025-11-14",
    es: {
      title: "Solicitud de Exención de Tarifas de Registros Públicos",
      description:
        "Solicite una exención o reducción de las tarifas de copia asociadas con una solicitud de registros públicos.",
      category: "Registros Públicos",
    },
  },
  {
    id: "meeting-minutes-archive-request",
    title: "Historical Meeting Minutes Request Form",
    description: "Request copies of Council, Planning Commission, or advisory board minutes not yet posted online.",
    category: "Public Records",
    fileUrl: "/documents/forms/meeting-minutes-archive-request.pdf",
    fileType: "PDF",
    fileSizeLabel: "92 KB",
    lastUpdated: "2025-02-18",
    es: {
      title: "Formulario de Solicitud de Actas Históricas de Reuniones",
      description:
        "Solicite copias de actas del Concejo, la Comisión de Planificación o juntas asesoras que aún no estén publicadas en línea.",
      category: "Registros Públicos",
    },
  },
  {
    id: "gis-data-request",
    title: "GIS and Infrastructure Map Data Request",
    description: "Request digital GIS layers or printed maps of city infrastructure, zoning, or parcel boundaries.",
    category: "Public Records",
    fileUrl: "/documents/forms/gis-data-request.pdf",
    fileType: "PDF",
    fileSizeLabel: "126 KB",
    lastUpdated: "2025-12-09",
    es: {
      title: "Solicitud de Datos GIS y Mapas de Infraestructura",
      description:
        "Solicite capas GIS digitales o mapas impresos de infraestructura de la ciudad, zonificación o límites de parcelas.",
      category: "Registros Públicos",
    },
  },
  {
    id: "water-service-application",
    title: "New Water Service Application",
    description: "Open a new water and sewer account for a residential or commercial address.",
    category: "Utility Services",
    fileUrl: "/documents/forms/water-service-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "148 KB",
    lastUpdated: "2026-01-22",
    es: {
      title: "Solicitud de Nuevo Servicio de Agua",
      description: "Abra una nueva cuenta de agua y alcantarillado para una dirección residencial o comercial.",
      category: "Servicios de Utilidad",
    },
  },
  {
    id: "water-service-transfer",
    title: "Water Service Transfer Form",
    description: "Transfer an existing water and sewer account to a new owner or tenant at the same address.",
    category: "Utility Services",
    fileUrl: "/documents/forms/water-service-transfer.pdf",
    fileType: "PDF",
    fileSizeLabel: "120 KB",
    lastUpdated: "2025-08-13",
    es: {
      title: "Formulario de Transferencia de Servicio de Agua",
      description:
        "Transfiera una cuenta de agua y alcantarillado existente a un nuevo propietario o inquilino en la misma dirección.",
      category: "Servicios de Utilidad",
    },
  },
  {
    id: "final-read-request",
    title: "Final Meter Read Request Form",
    description: "Request a final water meter read before closing an account when moving out of a property.",
    category: "Utility Services",
    fileUrl: "/documents/forms/final-read-request.pdf",
    fileType: "PDF",
    fileSizeLabel: "94 KB",
    lastUpdated: "2025-03-27",
    es: {
      title: "Solicitud de Lectura Final del Medidor",
      description:
        "Solicite una lectura final del medidor de agua antes de cerrar una cuenta al mudarse de una propiedad.",
      category: "Servicios de Utilidad",
    },
  },
  {
    id: "stormwater-credit-application",
    title: "Stormwater Utility Credit Application",
    description: "Apply for a reduced stormwater utility fee based on approved on-site stormwater controls.",
    category: "Utility Services",
    fileUrl: "/documents/forms/stormwater-credit-application.pdf",
    fileType: "PDF",
    fileSizeLabel: "196 KB",
    lastUpdated: "2026-06-02",
    es: {
      title: "Solicitud de Crédito de Servicio de Aguas Pluviales",
      description:
        "Solicite una tarifa reducida de servicio de aguas pluviales basada en controles de aguas pluviales aprobados en el sitio.",
      category: "Servicios de Utilidad",
    },
  },
  {
    id: "utility-billing-payment-plan",
    title: "Utility Billing Payment Plan Request",
    description: "Request a payment plan for a past-due water, sewer, or stormwater utility balance.",
    category: "Utility Services",
    fileUrl: "/documents/forms/utility-billing-payment-plan.pdf",
    fileType: "PDF",
    fileSizeLabel: "102 KB",
    lastUpdated: "2025-01-30",
    es: {
      title: "Solicitud de Plan de Pago de Facturación de Servicios",
      description:
        "Solicite un plan de pago para un saldo vencido de agua, alcantarillado o servicio de aguas pluviales.",
      category: "Servicios de Utilidad",
    },
  },
  {
    id: "backflow-prevention-test-report",
    title: "Backflow Prevention Device Test Report",
    description:
      "Required annual certification form for licensed testers reporting backflow prevention device inspections.",
    category: "Contractor Documents",
    fileUrl: "/documents/forms/backflow-prevention-test-report.pdf",
    fileType: "PDF",
    fileSizeLabel: "142 KB",
    lastUpdated: "2025-10-01",
    es: {
      title: "Informe de Prueba de Dispositivo de Prevención de Retroflujo",
      description:
        "Formulario de certificación anual requerido para probadores licenciados que reportan inspecciones de dispositivos de prevención de retroflujo.",
      category: "Documentos de Contratistas",
    },
  },
  {
    id: "contractor-registration",
    title: "Contractor Registration Form",
    description: "Required annual registration for contractors performing permitted work within Bellwood city limits.",
    category: "Contractor Documents",
    fileUrl: "/documents/forms/contractor-registration.pdf",
    fileType: "PDF",
    fileSizeLabel: "168 KB",
    lastUpdated: "2026-01-05",
    es: {
      title: "Formulario de Registro de Contratista",
      description:
        "Registro anual requerido para contratistas que realicen trabajos permitidos dentro de los límites de la ciudad de Bellwood.",
      category: "Documentos de Contratistas",
    },
  },
  {
    id: "certificate-of-insurance-form",
    title: "Certificate of Insurance Submission Form",
    description:
      "Cover sheet for contractors submitting proof of general liability and workers' compensation insurance.",
    category: "Contractor Documents",
    fileUrl: "/documents/forms/certificate-of-insurance-form.pdf",
    fileType: "PDF",
    fileSizeLabel: "86 KB",
    lastUpdated: "2025-06-11",
    es: {
      title: "Formulario de Presentación de Certificado de Seguro",
      description:
        "Hoja de portada para contratistas que presenten comprobante de seguro de responsabilidad civil general y compensación laboral.",
      category: "Documentos de Contratistas",
    },
  },
  {
    id: "prevailing-wage-certification",
    title: "Prevailing Wage Certification Form",
    description: "Required wage certification for contractors and subcontractors working on public bid projects.",
    category: "Contractor Documents",
    fileUrl: "/documents/forms/prevailing-wage-certification.pdf",
    fileType: "PDF",
    fileSizeLabel: "156 KB",
    lastUpdated: "2025-07-28",
    es: {
      title: "Formulario de Certificación de Salario Predominante",
      description:
        "Certificación salarial requerida para contratistas y subcontratistas que trabajen en proyectos de licitación pública.",
      category: "Documentos de Contratistas",
    },
  },
  {
    id: "bid-bond-form",
    title: "Bid Bond Form",
    description: "Standard bid bond form required with sealed bid submissions on public works construction contracts.",
    category: "Contractor Documents",
    fileUrl: "/documents/forms/bid-bond-form.pdf",
    fileType: "PDF",
    fileSizeLabel: "112 KB",
    lastUpdated: "2025-04-09",
    es: {
      title: "Formulario de Fianza de Oferta",
      description:
        "Formulario estándar de fianza de oferta requerido con las presentaciones de ofertas selladas en contratos de construcción de obras públicas.",
      category: "Documentos de Contratistas",
    },
  },
];
