import type { Meeting } from "./types";

export const meetings: Meeting[] = [
  {
    id: "council-regular-aug-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session covering the consent agenda, a public hearing on the Bridge Street resurfacing contract, and committee reports.",
    date: "2026-08-04",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-08-04.pdf",
    minutesUrl: "/documents/council-minutes-2026-07-07.pdf",
  },
  {
    id: "planning-commission-aug-2026",
    title: "Planning Commission Meeting",
    body: "Review of a proposed rezoning application on Maple Avenue and a preliminary site plan for the Riverside Drive mixed-use development.",
    date: "2026-08-11",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/planning-agenda-2026-08-11.pdf",
  },
  {
    id: "parks-board-aug-2026",
    title: "Parks and Recreation Board Meeting",
    body: "Discussion of the fall recreation program schedule and an update on the Eastside Trail extension project.",
    date: "2026-08-13",
    time: "4:00 PM",
    location: "Community Room, Eastside Recreation Center, 415 Birch Street",
    agendaUrl: "/documents/parks-board-agenda-2026-08-13.pdf",
  },
  {
    id: "stormwater-advisory-aug-2026",
    title: "Stormwater Advisory Committee Meeting",
    body: "Annual review of the stormwater management plan and public comment on proposed drainage improvements near Willow Creek.",
    date: "2026-08-18",
    time: "6:00 PM",
    location: "Public Works Annex, 220 Industrial Parkway",
    agendaUrl: "/documents/stormwater-agenda-2026-08-18.pdf",
  },
  {
    id: "council-regular-jul-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the annual paving schedule and the updated fee ordinance for stormwater management.",
    date: "2026-07-07",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-07-07.pdf",
    minutesUrl: "/documents/council-minutes-2026-07-07.pdf",
  },
  {
    id: "budget-workshop-sep-2026",
    title: "City Council Budget Workshop",
    body: "Public workshop on the proposed fiscal year budget, including capital improvement priorities for streets, water infrastructure, and parks.",
    date: "2026-09-09",
    time: "6:00 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/budget-workshop-agenda-2026-09-09.pdf",
  },
  {
    id: "planning-commission-jun-2026",
    title: "Planning Commission Meeting",
    body: "Reviewed and approved the preliminary plat for the Oakhill subdivision, phase two.",
    date: "2026-06-09",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    minutesUrl: "/documents/planning-minutes-2026-06-09.pdf",
  },
];
