import type { Meeting } from "./types";
import { shiftIso, shiftUrlDate } from "@/lib/dates";

// Dates below are written against the dataset anchor in lib/dates. They are shifted onto
// the current timeline at build time, in whole weeks so each body keeps its weekday.
const rawMeetings: Meeting[] = [
  {
    id: "council-regular-aug-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session covering the consent agenda, a public hearing on the Bridge Street resurfacing contract, and committee reports.",
    date: "2026-08-04",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-08-04.pdf",
    minutesUrl: "/documents/council-minutes-2026-07-07.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual que incluye la agenda de consentimiento, una audiencia pública sobre el contrato de repavimentación de la calle Bridge, e informes de comités.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "planning-commission-aug-2026",
    title: "Planning Commission Meeting",
    body: "Review of a proposed rezoning application on Maple Avenue and a preliminary site plan for the Riverside Drive mixed-use development.",
    date: "2026-08-11",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/planning-agenda-2026-08-11.pdf",
    es: {
      title: "Reunión de la Comisión de Planificación",
      body: "Revisión de una solicitud propuesta de recalificación de zonificación en la Avenida Maple y un plan de sitio preliminar para el desarrollo de uso mixto en Riverside Drive.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "parks-board-aug-2026",
    title: "Parks and Recreation Board Meeting",
    body: "Discussion of the fall recreation program schedule and an update on the Eastside Trail extension project.",
    date: "2026-08-13",
    time: "4:00 PM",
    location: "Community Room, Eastside Recreation Center, 415 Birch Street",
    agendaUrl: "/documents/parks-board-agenda-2026-08-13.pdf",
    es: {
      title: "Reunión de la Junta de Parques y Recreación",
      body: "Discusión del calendario de programas recreativos de otoño y una actualización sobre el proyecto de extensión del sendero Eastside.",
      location: "Salón Comunitario, Centro Recreativo Eastside, 415 Birch Street",
    },
  },
  {
    id: "stormwater-advisory-aug-2026",
    title: "Stormwater Advisory Committee Meeting",
    body: "Annual review of the stormwater management plan and public comment on proposed drainage improvements near Willow Creek.",
    date: "2026-08-18",
    time: "6:00 PM",
    location: "Public Works Annex, 220 Industrial Parkway",
    agendaUrl: "/documents/stormwater-agenda-2026-08-18.pdf",
    es: {
      title: "Reunión del Comité Asesor de Aguas Pluviales",
      body: "Revisión anual del plan de gestión de aguas pluviales y comentarios públicos sobre las mejoras de drenaje propuestas cerca de Willow Creek.",
      location: "Anexo de Obras Públicas, 220 Industrial Parkway",
    },
  },
  {
    id: "council-regular-jul-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the annual paving schedule and the updated fee ordinance for stormwater management.",
    date: "2026-07-07",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-07-07.pdf",
    minutesUrl: "/documents/council-minutes-2026-07-07.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó el calendario anual de pavimentación y la ordenanza de tarifas actualizada para la gestión de aguas pluviales.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "planning-commission-jun-2026",
    title: "Planning Commission Meeting",
    body: "Reviewed and approved the preliminary plat for the Oakhill subdivision, phase two.",
    date: "2026-06-09",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/planning-agenda-2026-06-09.pdf",
    minutesUrl: "/documents/planning-minutes-2026-06-09.pdf",
    es: {
      title: "Reunión de la Comisión de Planificación",
      body: "Se revisó y aprobó el plano preliminar de la segunda fase de la subdivisión Oakhill.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "council-regular-jun-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the bid award for the Oakhill lift station rehabilitation and heard a presentation on the capital improvement plan.",
    date: "2026-06-02",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-06-02.pdf",
    minutesUrl: "/documents/council-minutes-2026-06-02.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó la adjudicación de la licitación para la rehabilitación de la estación de bombeo de Oakhill y se presentó el plan de mejoras de capital.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "parks-board-may-2026",
    title: "Parks and Recreation Board Meeting",
    body: "Approved the summer recreation program schedule and reviewed bids for phase two of the Eastside Trail extension.",
    date: "2026-05-14",
    time: "4:00 PM",
    location: "Community Room, Eastside Recreation Center, 415 Birch Street",
    agendaUrl: "/documents/parks-board-agenda-2026-05-14.pdf",
    minutesUrl: "/documents/parks-board-minutes-2026-05-14.pdf",
    es: {
      title: "Reunión de la Junta de Parques y Recreación",
      body: "Se aprobó el calendario del programa recreativo de verano y se revisaron las ofertas para la fase dos de la extensión del sendero Eastside.",
      location: "Salón Comunitario, Centro Recreativo Eastside, 415 Birch Street",
    },
  },
  {
    id: "stormwater-advisory-may-2026",
    title: "Stormwater Advisory Committee Meeting",
    body: "Heard public comment on the Willow Creek drainage improvement proposal and recommended it advance to City Council for funding consideration.",
    date: "2026-05-28",
    time: "6:00 PM",
    location: "Public Works Annex, 220 Industrial Parkway",
    agendaUrl: "/documents/stormwater-agenda-2026-05-28.pdf",
    minutesUrl: "/documents/stormwater-minutes-2026-05-28.pdf",
    es: {
      title: "Reunión del Comité Asesor de Aguas Pluviales",
      body: "Se recibieron comentarios públicos sobre la propuesta de mejoras de drenaje de Willow Creek y se recomendó que avance al Concejo Municipal para su financiamiento.",
      location: "Anexo de Obras Públicas, 220 Industrial Parkway",
    },
  },
  {
    id: "budget-workshop-may-2026",
    title: "City Council Budget Workshop",
    body: "Public workshop on the proposed fiscal year budget, including capital improvement priorities for streets, water infrastructure, and parks.",
    date: "2026-05-05",
    time: "6:00 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/budget-workshop-agenda-2026-05-05.pdf",
    minutesUrl: "/documents/budget-workshop-minutes-2026-05-05.pdf",
    es: {
      title: "Taller Presupuestario del Concejo Municipal",
      body: "Taller público sobre el presupuesto propuesto para el año fiscal, incluyendo las prioridades de mejoras de capital para calles, infraestructura de agua y parques.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "council-regular-apr-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the pre-bid schedule for the Eastside Trail extension and heard an update on the Willow Creek drainage study.",
    date: "2026-04-07",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-04-07.pdf",
    minutesUrl: "/documents/council-minutes-2026-04-07.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó el calendario previo a la licitación para la extensión del sendero Eastside y se presentó una actualización sobre el estudio de drenaje de Willow Creek.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "planning-commission-mar-2026",
    title: "Planning Commission Meeting",
    body: "Reviewed the annual comprehensive plan update and recommended minor amendments to the zoning map along Riverside Drive.",
    date: "2026-03-10",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/planning-agenda-2026-03-10.pdf",
    minutesUrl: "/documents/planning-minutes-2026-03-10.pdf",
    es: {
      title: "Reunión de la Comisión de Planificación",
      body: "Se revisó la actualización anual del plan integral y se recomendaron enmiendas menores al mapa de zonificación a lo largo de Riverside Drive.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "council-regular-feb-2026",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the bid solicitation for Oak Avenue sidewalk and ADA ramp construction.",
    date: "2026-02-03",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    agendaUrl: "/documents/council-agenda-2026-02-03.pdf",
    minutesUrl: "/documents/council-minutes-2026-02-03.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó la licitación para la construcción de aceras y rampas ADA en la Avenida Oak.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "parks-board-jan-2026",
    title: "Parks and Recreation Board Meeting",
    body: "Reviewed winter program attendance and approved the pavilion reservation calendar for the coming season.",
    date: "2026-01-08",
    time: "4:00 PM",
    location: "Community Room, Eastside Recreation Center, 415 Birch Street",
    agendaUrl: "/documents/parks-board-agenda-2026-01-08.pdf",
    minutesUrl: "/documents/parks-board-minutes-2026-01-08.pdf",
    es: {
      title: "Reunión de la Junta de Parques y Recreación",
      body: "Se revisó la asistencia a los programas de invierno y se aprobó el calendario de reservas de pabellones para la próxima temporada.",
      location: "Salón Comunitario, Centro Recreativo Eastside, 415 Birch Street",
    },
  },
  {
    id: "council-regular-dec-2025",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the fleet vehicle purchase award and adopted the final fiscal year budget.",
    date: "2025-12-01",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    minutesUrl: "/documents/council-minutes-2025-12-01.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó la adjudicación de la compra de vehículos de flota y se adoptó el presupuesto final del año fiscal.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "stormwater-advisory-oct-2025",
    title: "Stormwater Advisory Committee Meeting",
    body: "Reviewed findings from the 4th Avenue culvert replacement project and discussed priorities for the following year's drainage improvements.",
    date: "2025-10-22",
    time: "6:00 PM",
    location: "Public Works Annex, 220 Industrial Parkway",
    minutesUrl: "/documents/stormwater-minutes-2025-10-22.pdf",
    es: {
      title: "Reunión del Comité Asesor de Aguas Pluviales",
      body: "Se revisaron los resultados del proyecto de reemplazo de la alcantarilla de la 4ta Avenida y se discutieron las prioridades para las mejoras de drenaje del año siguiente.",
      location: "Anexo de Obras Públicas, 220 Industrial Parkway",
    },
  },
  {
    id: "planning-commission-sep-2025",
    title: "Planning Commission Meeting",
    body: "Approved a preliminary plat for a small residential subdivision off Oak Avenue and heard a report on citywide sidewalk gap analysis.",
    date: "2025-09-08",
    time: "5:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    minutesUrl: "/documents/planning-minutes-2025-09-08.pdf",
    es: {
      title: "Reunión de la Comisión de Planificación",
      body: "Se aprobó un plano preliminar para una pequeña subdivisión residencial cerca de la Avenida Oak y se presentó un informe sobre el análisis de brechas de aceras en toda la ciudad.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "council-regular-aug-2025",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved emergency repair funding following the July severe thunderstorm and heard a report on the recycling cart replacement rollout.",
    date: "2025-08-04",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    minutesUrl: "/documents/council-minutes-2025-08-04.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó el financiamiento de reparaciones de emergencia tras la tormenta severa de julio y se presentó un informe sobre la distribución de contenedores de reciclaje.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
  {
    id: "council-regular-mar-2025",
    title: "City Council Regular Meeting",
    body: "Monthly regular session. Approved the Oak Avenue sidewalk and ADA ramp construction contract award.",
    date: "2025-03-04",
    time: "6:30 PM",
    location: "Council Chambers, Bellwood City Hall, 100 Municipal Way",
    minutesUrl: "/documents/council-minutes-2025-03-04.pdf",
    es: {
      title: "Sesión Ordinaria del Concejo Municipal",
      body: "Sesión ordinaria mensual. Se aprobó la adjudicación del contrato de construcción de aceras y rampas ADA en la Avenida Oak.",
      location: "Salón del Concejo, Ayuntamiento de Bellwood, 100 Municipal Way",
    },
  },
];

export const meetings: Meeting[] = rawMeetings.map((meeting) => ({
  ...meeting,
  date: shiftIso(meeting.date),
  agendaUrl: meeting.agendaUrl ? shiftUrlDate(meeting.agendaUrl) : undefined,
  minutesUrl: meeting.minutesUrl ? shiftUrlDate(meeting.minutesUrl) : undefined,
}));
