import type { Notice } from "./types";
import { shiftIso } from "@/lib/dates";

// Dates below are written against the dataset anchor in lib/dates and shifted onto the
// current timeline at build time. Bodies that name a date use a {date:YYYY-MM-DD} token
// so the prose moves with the notice instead of contradicting it.
const rawNotices: Notice[] = [
  {
    id: "water-main-repair-elm",
    title: "Emergency water main repair on Elm Street",
    body: "Crews are repairing a broken water main between 4th Avenue and 6th Avenue. Expect low water pressure in the surrounding blocks through the end of the day. Elm Street is closed to through traffic while repairs are underway.",
    date: "2026-07-26",
    department: "Water and Sewer Division",
    urgent: true,
    active: true,
    es: {
      title: "Reparación de emergencia de tubería principal de agua en la calle Elm",
      body: "Las cuadrillas están reparando una tubería principal de agua rota entre la 4ta Avenida y la 6ta Avenida. Se espera baja presión de agua en las cuadras cercanas hasta el final del día. La calle Elm está cerrada al tráfico de paso mientras se realizan las reparaciones.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "boil-water-notice-northside",
    title: "Boil water notice lifted for the Northside district",
    body: "Water quality testing following last week's main repair has confirmed the Northside district's water supply meets all safety standards. The boil water notice issued on {date:2026-07-20} is no longer in effect.",
    date: "2026-07-25",
    department: "Water and Sewer Division",
    urgent: false,
    active: true,
    es: {
      title: "Se levanta el aviso de hervir el agua para el distrito Northside",
      body: "Las pruebas de calidad del agua tras la reparación de la tubería principal de la semana pasada han confirmado que el suministro de agua del distrito Northside cumple con todas las normas de seguridad. El aviso de hervir el agua emitido el {date:2026-07-20} ya no está vigente.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "boil-water-advisory-northside",
    title: "Boil water advisory issued for the Northside district",
    body: "Following the water main repair on Elm Street, a precautionary boil water advisory is in effect for the Northside district, bounded by 4th Avenue, Birch Street, and the rail corridor. Residents should bring tap water to a rolling boil for one minute before drinking or cooking until testing confirms the system is clear.",
    date: "2026-07-20",
    department: "Water and Sewer Division",
    urgent: true,
    active: false,
    es: {
      title: "Aviso de hervir el agua emitido para el distrito Northside",
      body: "Tras la reparación de la tubería principal en la calle Elm, un aviso preventivo de hervir el agua está vigente para el distrito Northside, delimitado por la 4ta Avenida, la calle Birch y el corredor ferroviario. Se recomienda a los residentes hervir el agua del grifo durante un minuto antes de beberla o cocinar hasta que las pruebas confirmen que el sistema está limpio.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "bid-solicitation-oakhill-lift-station",
    title: "Bid solicitation: Oakhill lift station rehabilitation",
    body: "Bellwood Public Works is soliciting sealed bids from qualified contractors for the rehabilitation of the Oakhill sewer lift station, including pump replacement and electrical upgrades. Bid documents are available from the Purchasing Office. Bids are due by 2:00 PM on {date:2026-08-21}.",
    date: "2026-07-17",
    department: "Water and Sewer Division",
    urgent: false,
    active: true,
    es: {
      title: "Licitación: rehabilitación de la estación de bombeo de Oakhill",
      body: "Bellwood Public Works solicita ofertas selladas de contratistas calificados para la rehabilitación de la estación de bombeo de alcantarillado de Oakhill, incluyendo el reemplazo de bombas y mejoras eléctricas. Los documentos de la licitación están disponibles en la Oficina de Compras. Las ofertas vencen a las 2:00 PM del {date:2026-08-21}.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "public-hearing-maple-rezoning",
    title: "Public hearing scheduled on Maple Avenue rezoning application",
    body: "The Planning Commission will hold a public hearing on a proposed rezoning of the 900 block of Maple Avenue from single-family residential to mixed-use. The hearing is part of the Planning Commission meeting on {date:2026-08-11}. Written comments may be submitted in advance through the Planning Office.",
    date: "2026-07-15",
    department: "City Clerk's Office",
    urgent: false,
    active: true,
    es: {
      title: "Audiencia pública programada sobre la recalificación de la Avenida Maple",
      body: "La Comisión de Planificación llevará a cabo una audiencia pública sobre una propuesta de recalificación de la cuadra 900 de la Avenida Maple, de residencial unifamiliar a uso mixto. La audiencia forma parte de la reunión de la Comisión de Planificación del {date:2026-08-11}. Los comentarios por escrito pueden enviarse con anticipación a través de la Oficina de Planificación.",
      department: "Oficina del Secretario Municipal",
    },
  },
  {
    id: "road-closure-bridge-street",
    title: "Bridge Street closed for resurfacing through August",
    body: "Bridge Street between Oak Avenue and the river crossing is closed to vehicle traffic while crews complete a full-depth resurfacing project. A signed detour routes traffic via Oak Avenue and Riverside Drive. Pedestrian access remains open.",
    date: "2026-07-14",
    department: "Streets Division",
    urgent: false,
    active: true,
    es: {
      title: "Calle Bridge cerrada por repavimentación durante agosto",
      body: "La calle Bridge entre la Avenida Oak y el cruce del río está cerrada al tráfico vehicular mientras las cuadrillas completan un proyecto de repavimentación total. Un desvío señalizado dirige el tráfico por la Avenida Oak y Riverside Drive. El acceso peatonal permanece abierto.",
      department: "División de Calles",
    },
  },
  {
    id: "sidewalk-closure-birch-street",
    title: "Sidewalk closure on Birch Street near the recreation center",
    body: "The sidewalk along the 400 block of Birch Street will be closed for curb ramp reconstruction to bring the corner into compliance with accessibility standards. Pedestrians should use the marked detour on the opposite side of the street. Work is expected to take approximately two weeks.",
    date: "2026-07-10",
    department: "Streets Division",
    urgent: false,
    active: true,
    es: {
      title: "Cierre de acera en la calle Birch cerca del centro recreativo",
      body: "La acera de la cuadra 400 de la calle Birch estará cerrada para la reconstrucción de la rampa de la esquina y así cumplir con las normas de accesibilidad. Los peatones deben usar el desvío señalizado en el lado opuesto de la calle. Se espera que el trabajo tome aproximadamente dos semanas.",
      department: "División de Calles",
    },
  },
  {
    id: "stormwater-fee-adjustment",
    title: "Stormwater utility fee adjustment approved",
    body: "City Council approved a modest adjustment to the stormwater utility fee effective with the next billing cycle. Property owners with approved on-site stormwater controls remain eligible for a reduced rate.",
    date: "2026-06-02",
    department: "Stormwater Division",
    urgent: false,
    active: true,
    es: {
      title: "Aprobado ajuste a la tarifa de servicio de aguas pluviales",
      body: "El Concejo Municipal aprobó un ajuste modesto a la tarifa de servicio de aguas pluviales, vigente a partir del próximo ciclo de facturación. Los propietarios con controles de aguas pluviales aprobados en el sitio siguen siendo elegibles para una tarifa reducida.",
      department: "División de Aguas Pluviales",
    },
  },
  {
    id: "willow-creek-drainage-hearing",
    title: "Public hearing on proposed Willow Creek drainage improvements",
    body: "The Stormwater Advisory Committee will accept public comment on proposed drainage improvements near Willow Creek, intended to reduce recurring street flooding in the Southside district. The hearing is part of the committee meeting on {date:2026-08-18} at the Public Works Annex.",
    date: "2026-05-28",
    department: "Stormwater Division",
    urgent: false,
    active: true,
    es: {
      title: "Audiencia pública sobre mejoras de drenaje propuestas en Willow Creek",
      body: "El Comité Asesor de Aguas Pluviales recibirá comentarios públicos sobre las mejoras de drenaje propuestas cerca de Willow Creek, destinadas a reducir las inundaciones recurrentes de calles en el distrito Southside. La audiencia forma parte de la reunión del comité del {date:2026-08-18} en el Anexo de Obras Públicas.",
      department: "División de Aguas Pluviales",
    },
  },
  {
    id: "spring-flushing-program-archive",
    title: "Spring hydrant flushing program completed",
    body: "The annual hydrant flushing program, which can cause temporary water discoloration, wrapped up in all city districts as of this notice. Residents who still notice discolored water are encouraged to run a cold tap for a few minutes.",
    date: "2026-04-30",
    department: "Water and Sewer Division",
    urgent: false,
    active: false,
    es: {
      title: "Concluye el programa de purga de hidrantes de primavera",
      body: "El programa anual de purga de hidrantes, que puede causar decoloración temporal del agua, concluyó en todos los distritos de la ciudad según este aviso. Se recomienda a los residentes que aún noten agua decolorada dejar correr una llave de agua fría durante unos minutos.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "bid-solicitation-eastside-trail",
    title: "Bid solicitation: Eastside Trail extension, phase two",
    body: "Sealed bids are being accepted for phase two construction of the Eastside Trail extension, connecting Birch Street to the Riverside Drive greenway. Bid documents are available from the Purchasing Office. A mandatory pre-bid site walk will be held on {date:2026-04-22} at the trailhead on Birch Street.",
    date: "2026-04-08",
    department: "Parks and Recreation",
    urgent: false,
    active: false,
    es: {
      title: "Licitación: extensión del sendero Eastside, fase dos",
      body: "Se aceptan ofertas selladas para la construcción de la fase dos de la extensión del sendero Eastside, que conectará la calle Birch con el corredor verde de Riverside Drive. Los documentos de la licitación están disponibles en la Oficina de Compras. Se realizará una visita obligatoria previa a la oferta el {date:2026-04-22} en la entrada del sendero en la calle Birch.",
      department: "Parques y Recreación",
    },
  },
  {
    id: "seasonal-water-restrictions-summer",
    title: "Seasonal outdoor watering schedule now in effect",
    body: "The annual summer outdoor watering schedule is now in effect through {date:2026-09-30}. Addresses ending in an odd number may water lawns and gardens on odd-numbered calendar days, and even-numbered addresses on even-numbered days, between 6:00 PM and 10:00 AM.",
    date: "2026-06-01",
    department: "Water and Sewer Division",
    urgent: false,
    active: true,
    es: {
      title: "Entra en vigencia el calendario estacional de riego al aire libre",
      body: "El calendario anual de riego exterior de verano está vigente hasta el {date:2026-09-30}. Las direcciones que terminan en número impar pueden regar césped y jardines en días impares del calendario, y las direcciones pares en días pares, entre las 6:00 PM y las 10:00 AM.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "curbside-yard-waste-extended",
    title: "Curbside yard waste collection extended through November",
    body: "In response to resident requests, biweekly curbside yard waste collection has been extended through the end of November this year. Bundled brush and bagged leaves should be placed at the curb by 7:00 AM on the scheduled collection day.",
    date: "2025-10-06",
    department: "Sanitation Division",
    urgent: false,
    active: false,
    es: {
      title: "Se extiende la recolección de desechos de jardín en la acera hasta noviembre",
      body: "En respuesta a las solicitudes de los residentes, la recolección quincenal en la acera de desechos de jardín se ha extendido hasta finales de noviembre de este año. Las ramas atadas y las hojas embolsadas deben colocarse en la acera antes de las 7:00 AM el día de recolección programado.",
      department: "División de Saneamiento",
    },
  },
  {
    id: "snow-emergency-declared-jan-2026",
    title: "Snow emergency declared for the overnight winter storm",
    body: "A snow emergency has been declared effective 6:00 PM. Parking is prohibited on designated snow emergency routes until the emergency is lifted. Vehicles left on emergency routes are subject to towing. Priority routes will be plowed first, followed by residential streets.",
    date: "2026-01-17",
    department: "Streets Division",
    urgent: true,
    active: false,
    es: {
      title: "Se declara emergencia por nieve para la tormenta invernal nocturna",
      body: "Se ha declarado una emergencia por nieve vigente a partir de las 6:00 PM. Se prohíbe estacionar en las rutas designadas de emergencia por nieve hasta que se levante la emergencia. Los vehículos dejados en rutas de emergencia están sujetos a remolque. Las rutas prioritarias se despejarán primero, seguidas de las calles residenciales.",
      department: "División de Calles",
    },
  },
  {
    id: "winter-storm-advisory-archive",
    title: "Winter storm advisory: parking restrictions lifted",
    body: "Snow emergency parking restrictions issued during the January storm have been lifted. Residential streets have been fully plowed and normal parking rules are back in effect.",
    date: "2026-01-18",
    department: "Streets Division",
    urgent: false,
    active: false,
    es: {
      title: "Aviso de tormenta invernal: se levantan las restricciones de estacionamiento",
      body: "Se han levantado las restricciones de estacionamiento por emergencia de nieve emitidas durante la tormenta de enero. Las calles residenciales han sido completamente despejadas y las reglas normales de estacionamiento están nuevamente en vigencia.",
      department: "División de Calles",
    },
  },
  {
    id: "city-hall-closure-holiday",
    title: "City offices closed for Labor Day",
    body: "All Bellwood Public Works offices, including the permitting counter and utility billing office, will be closed on Labor Day. Waste and recycling collection will run one day later than usual that week.",
    date: "2026-08-15",
    department: "City Clerk's Office",
    urgent: false,
    active: true,
    es: {
      title: "Oficinas de la ciudad cerradas por el Día del Trabajo",
      body: "Todas las oficinas de Bellwood Public Works, incluyendo el mostrador de permisos y la oficina de facturación de servicios públicos, permanecerán cerradas el Día del Trabajo. La recolección de basura y reciclaje se realizará un día más tarde de lo habitual esa semana.",
      department: "Oficina del Secretario Municipal",
    },
  },
  {
    id: "city-hall-closure-new-years",
    title: "City offices closed for New Year's Day",
    body: "All Bellwood Public Works offices will be closed on New Year's Day. Waste and recycling collection scheduled for that day will be collected on the next regular business day, with all subsequent pickups that week shifting back by one day.",
    date: "2025-12-29",
    department: "City Clerk's Office",
    urgent: false,
    active: false,
    es: {
      title: "Oficinas de la ciudad cerradas por el Año Nuevo",
      body: "Todas las oficinas de Bellwood Public Works estarán cerradas el Día de Año Nuevo. La recolección de basura y reciclaje programada para ese día se realizará el siguiente día hábil regular, y todas las recolecciones posteriores de esa semana se retrasarán un día.",
      department: "Oficina del Secretario Municipal",
    },
  },
  {
    id: "bid-solicitation-fleet-vehicles",
    title: "Bid solicitation: replacement fleet vehicles",
    body: "Bellwood Public Works is accepting sealed bids for the purchase of six replacement service vehicles for the Streets and Water and Sewer Divisions. Specifications and bid forms are available from the Purchasing Office. Bids are due by 2:00 PM on {date:2025-12-05}.",
    date: "2025-11-10",
    department: "Streets Division",
    urgent: false,
    active: false,
    es: {
      title: "Licitación: vehículos de flota de reemplazo",
      body: "Bellwood Public Works acepta ofertas selladas para la compra de seis vehículos de servicio de reemplazo para las Divisiones de Calles y de Agua y Alcantarillado. Las especificaciones y los formularios de oferta están disponibles en la Oficina de Compras. Las ofertas vencen a las 2:00 PM del {date:2025-12-05}.",
      department: "División de Calles",
    },
  },
  {
    id: "leaf-collection-schedule-fall-2025",
    title: "Fall leaf collection schedule announced",
    body: "Loose leaf collection will run on a rotating district schedule from late October through early December. Residents should rake leaves to the curb, not into the street, by 7:00 AM on their district's scheduled week. Leaves placed in plastic bags will not be collected through this program.",
    date: "2025-10-01",
    department: "Sanitation Division",
    urgent: false,
    active: false,
    es: {
      title: "Se anuncia el calendario de recolección de hojas de otoño",
      body: "La recolección de hojas sueltas se realizará según un calendario rotativo por distrito desde finales de octubre hasta principios de diciembre. Los residentes deben rastrillar las hojas hacia la acera, no hacia la calle, antes de las 7:00 AM en la semana programada de su distrito. Las hojas colocadas en bolsas de plástico no serán recolectadas mediante este programa.",
      department: "División de Saneamiento",
    },
  },
  {
    id: "public-hearing-fee-ordinance",
    title: "Public hearing on proposed stormwater fee ordinance",
    body: "City Council will hold a public hearing on a proposed ordinance updating the stormwater utility fee schedule. The hearing is part of the regular Council meeting on {date:2026-07-07}. Residents may submit written comments to the City Clerk's Office prior to the meeting.",
    date: "2026-06-20",
    department: "City Clerk's Office",
    urgent: false,
    active: false,
    es: {
      title: "Audiencia pública sobre la propuesta de ordenanza de tarifas de aguas pluviales",
      body: "El Concejo Municipal llevará a cabo una audiencia pública sobre una propuesta de ordenanza que actualiza el cuadro de tarifas del servicio de aguas pluviales. La audiencia forma parte de la reunión ordinaria del Concejo del {date:2026-07-07}. Los residentes pueden enviar comentarios por escrito a la Oficina del Secretario Municipal antes de la reunión.",
      department: "Oficina del Secretario Municipal",
    },
  },
  {
    id: "water-main-break-oakhill",
    title: "Water main break repaired in the Oakhill subdivision",
    body: "Crews completed emergency repairs to a water main break on Cedar Court in the Oakhill subdivision. Water service has been restored to all affected addresses. Some residents may notice temporary discoloration as the system repressurizes.",
    date: "2025-09-12",
    department: "Water and Sewer Division",
    urgent: false,
    active: false,
    es: {
      title: "Se repara rotura de tubería principal de agua en la subdivisión Oakhill",
      body: "Las cuadrillas completaron las reparaciones de emergencia de una rotura de tubería principal de agua en Cedar Court, en la subdivisión Oakhill. El servicio de agua ha sido restablecido en todas las direcciones afectadas. Algunos residentes pueden notar decoloración temporal mientras el sistema se represuriza.",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "road-closure-4th-avenue-culvert",
    title: "4th Avenue closed for culvert replacement",
    body: "4th Avenue between Elm Street and the Willow Creek crossing is closed to all traffic while crews replace an aging stormwater culvert. A signed detour routes traffic via 6th Avenue. The closure is expected to last approximately three weeks.",
    date: "2025-08-04",
    department: "Stormwater Division",
    urgent: false,
    active: false,
    es: {
      title: "4ta Avenida cerrada por reemplazo de alcantarilla",
      body: "La 4ta Avenida entre la calle Elm y el cruce de Willow Creek está cerrada a todo tráfico mientras las cuadrillas reemplazan una alcantarilla pluvial deteriorada. Un desvío señalizado dirige el tráfico por la 6ta Avenida. Se espera que el cierre dure aproximadamente tres semanas.",
      department: "División de Aguas Pluviales",
    },
  },
  {
    id: "emergency-alert-severe-thunderstorm",
    title: "Emergency alert: severe thunderstorm warning in effect",
    body: "A severe thunderstorm warning is in effect for Bellwood and surrounding areas until 9:00 PM. Residents should avoid unnecessary travel. Public Works crews are on standby to respond to downed trees, flooded roadways, and storm-related outages.",
    date: "2025-07-19",
    department: "Streets Division",
    urgent: true,
    active: false,
    es: {
      title: "Alerta de emergencia: advertencia de tormenta severa vigente",
      body: "Una advertencia de tormenta severa está vigente para Bellwood y sus alrededores hasta las 9:00 PM. Se recomienda a los residentes evitar viajes innecesarios. Las cuadrillas de Obras Públicas están en espera para responder a árboles caídos, calles inundadas e interrupciones relacionadas con la tormenta.",
      department: "División de Calles",
    },
  },
  {
    id: "bid-solicitation-oak-avenue-sidewalks",
    title: "Bid solicitation: Oak Avenue sidewalk and ADA ramp construction",
    body: "Sealed bids are being solicited for new sidewalk construction and ADA-compliant curb ramps along Oak Avenue between 2nd Avenue and Maple Avenue. Bid documents are available from the Purchasing Office. Bids are due by 2:00 PM on {date:2025-03-06}.",
    date: "2025-02-10",
    department: "Streets Division",
    urgent: false,
    active: false,
    es: {
      title: "Licitación: construcción de aceras y rampas ADA en la Avenida Oak",
      body: "Se solicitan ofertas selladas para la construcción de nuevas aceras y rampas de acera conformes con la ADA a lo largo de la Avenida Oak entre la 2da Avenida y la Avenida Maple. Los documentos de la licitación están disponibles en la Oficina de Compras. Las ofertas vencen a las 2:00 PM del {date:2025-03-06}.",
      department: "División de Calles",
    },
  },
  {
    id: "recycling-cart-rollout-southside",
    title: "New recycling carts rolling out to the Southside district",
    body: "Households in the Southside district will receive new 65-gallon recycling carts this month as part of the citywide cart replacement program. Residents should place their old bin at the curb for pickup once the new cart is delivered. No action is required to receive a new cart.",
    date: "2025-03-17",
    department: "Sanitation Division",
    urgent: false,
    active: false,
    es: {
      title: "Nuevos contenedores de reciclaje se distribuyen en el distrito Southside",
      body: "Los hogares del distrito Southside recibirán nuevos contenedores de reciclaje de 65 galones este mes como parte del programa de reemplazo de contenedores en toda la ciudad. Los residentes deben colocar su contenedor antiguo en la acera para su recolección una vez que se entregue el nuevo. No se requiere ninguna acción para recibir un contenedor nuevo.",
      department: "División de Saneamiento",
    },
  },
];

export const notices: Notice[] = rawNotices.map((notice) => ({
  ...notice,
  date: shiftIso(notice.date),
}));
