import type { StaffMember } from "./types";

export const staff: StaffMember[] = [
  {
    id: "director",
    name: "Marcus Whitfield",
    title: "Director of Public Works",
    department: "Administration",
    extension: "1200",
    email: "mwhitfield@bellwoodpublicworks.example",
    photo: "/images/staff/director.jpg",
    photoAlt: "Portrait of Marcus Whitfield, Director of Public Works",
    es: {
      title: "Director de Obras Públicas",
      department: "Administración",
    },
  },
  {
    id: "deputy-director",
    name: "Colleen Vasquez",
    title: "Deputy Director of Public Works",
    department: "Administration",
    extension: "1201",
    email: "cvasquez@bellwoodpublicworks.example",
    photo: "/images/staff/deputy-director.jpg",
    photoAlt: "Portrait of Colleen Vasquez, Deputy Director of Public Works",
    es: {
      title: "Subdirectora de Obras Públicas",
      department: "Administración",
    },
  },
  {
    id: "water-sewer",
    name: "Renata Ibarra",
    title: "Water and Sewer Division Manager",
    department: "Water and Sewer Division",
    extension: "2201",
    email: "ribarra@bellwoodpublicworks.example",
    photo: "/images/staff/water-sewer.jpg",
    photoAlt: "Portrait of Renata Ibarra, Water and Sewer Division Manager",
    es: {
      title: "Gerente de la División de Agua y Alcantarillado",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "water-quality-supervisor",
    name: "Julian Foss",
    title: "Water Quality Supervisor",
    department: "Water and Sewer Division",
    extension: "2205",
    email: "jfoss@bellwoodpublicworks.example",
    photo: "/images/staff/water-quality-supervisor.jpg",
    photoAlt: "Portrait of Julian Foss, Water Quality Supervisor",
    es: {
      title: "Supervisor de Calidad del Agua",
      department: "División de Agua y Alcantarillado",
    },
  },
  {
    id: "streets",
    name: "Owen Baptiste",
    title: "Streets Division Manager",
    department: "Streets Division",
    extension: "2211",
    email: "obaptiste@bellwoodpublicworks.example",
    photo: "/images/staff/streets.jpg",
    photoAlt: "Portrait of Owen Baptiste, Streets Division Manager",
    es: {
      title: "Gerente de la División de Calles",
      department: "División de Calles",
    },
  },
  {
    id: "traffic-engineer",
    name: "Nadia Petrosyan",
    title: "City Traffic Engineer",
    department: "Streets Division",
    extension: "2214",
    email: "npetrosyan@bellwoodpublicworks.example",
    photo: "/images/staff/traffic-engineer.jpg",
    photoAlt: "Portrait of Nadia Petrosyan, City Traffic Engineer",
    es: {
      title: "Ingeniera de Tráfico de la Ciudad",
      department: "División de Calles",
    },
  },
  {
    id: "permits",
    name: "Priya Chandran",
    title: "Chief Building Inspector",
    department: "Building Permits and Inspections",
    extension: "2221",
    email: "pchandran@bellwoodpublicworks.example",
    photo: "/images/staff/permits.jpg",
    photoAlt: "Portrait of Priya Chandran, Chief Building Inspector",
    es: {
      title: "Inspectora Jefa de Construcción",
      department: "Permisos de Construcción e Inspecciones",
    },
  },
  {
    id: "plans-examiner",
    name: "Harold Yeboah",
    title: "Senior Plans Examiner",
    department: "Building Permits and Inspections",
    extension: "2224",
    email: "hyeboah@bellwoodpublicworks.example",
    photo: "/images/staff/plans-examiner.jpg",
    photoAlt: "Portrait of Harold Yeboah, Senior Plans Examiner",
    es: {
      title: "Examinador Principal de Planos",
      department: "Permisos de Construcción e Inspecciones",
    },
  },
  {
    id: "sanitation",
    name: "Devon Marsh",
    title: "Sanitation Division Manager",
    department: "Sanitation Division",
    extension: "2231",
    email: "dmarsh@bellwoodpublicworks.example",
    photo: "/images/staff/sanitation.jpg",
    photoAlt: "Portrait of Devon Marsh, Sanitation Division Manager",
    es: {
      title: "Gerente de la División de Saneamiento",
      department: "División de Saneamiento",
    },
  },
  {
    id: "parks",
    name: "Talia Nkemelu",
    title: "Parks and Recreation Manager",
    department: "Parks and Recreation",
    extension: "2241",
    email: "tnkemelu@bellwoodpublicworks.example",
    photo: "/images/staff/parks.jpg",
    photoAlt: "Portrait of Talia Nkemelu, Parks and Recreation Manager",
    es: {
      title: "Gerente de Parques y Recreación",
      department: "Parques y Recreación",
    },
  },
  {
    id: "stormwater",
    name: "Regina Alcott",
    title: "Stormwater Division Manager",
    department: "Stormwater Division",
    extension: "2261",
    email: "ralcott@bellwoodpublicworks.example",
    photo: "/images/staff/stormwater.jpg",
    photoAlt: "Portrait of Regina Alcott, Stormwater Division Manager",
    es: {
      title: "Gerente de la División de Aguas Pluviales",
      department: "División de Aguas Pluviales",
    },
  },
  {
    id: "clerk",
    name: "Samuel Okafor",
    title: "City Clerk",
    department: "City Clerk's Office",
    extension: "1210",
    email: "sokafor@bellwoodpublicworks.example",
    photo: "/images/staff/clerk.jpg",
    photoAlt: "Portrait of Samuel Okafor, City Clerk",
    es: {
      title: "Secretario Municipal",
      department: "Oficina del Secretario Municipal",
    },
  },
];
