import {
  Droplets,
  Route,
  Hammer,
  Recycle,
  Trees,
  Snowflake,
  CloudRain,
  CreditCard,
  Construction,
  FileCheck2,
  Trash2,
  FolderSearch,
  CalendarDays,
  Lightbulb,
  Signpost,
  FlaskConical,
  ShieldCheck,
  Accessibility,
  HardHat,
  Map,
  Leaf,
  type LucideIcon,
} from "lucide-react";

export const serviceIcons: Record<string, LucideIcon> = {
  droplets: Droplets,
  road: Route,
  hammer: Hammer,
  recycle: Recycle,
  trees: Trees,
  snowflake: Snowflake,
  "cloud-rain": CloudRain,
  "credit-card": CreditCard,
  "flask-conical": FlaskConical,
  "shield-check": ShieldCheck,
  accessibility: Accessibility,
  "hard-hat": HardHat,
  map: Map,
  leaf: Leaf,
  signpost: Signpost,
  "trash-2": Trash2,
};

export const quickActionIcons: Record<string, LucideIcon> = {
  "credit-card": CreditCard,
  construction: Construction,
  "file-check-2": FileCheck2,
  "trash-2": Trash2,
  "folder-search": FolderSearch,
  "calendar-days": CalendarDays,
  lightbulb: Lightbulb,
  signpost: Signpost,
};
